language: perl
perl:
  - "blead"
  - "5.20.0"
  - "5.18.2_thr"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8.9_thr"
  - "5.8.9"
  - "5.8.1"
matrix:
  fast_finish: true
  allow_failures:
    - perl: 5.8.1
    - perl: 5.6.2
  include:
    - perl: 5.18.2
      env:  EXTENDED_TESTING=1 COVERAGE=1
    - perl: "5.6.2"
      script: perl /home/travis/perl5/perlbrew/perls/5.6.2/bin/prove -r -Ilib -Iinc "t"
before_install:
  - export DIST_INKT_PROFILE="Dist::Inkt::Profile::TOBYINK"
  - git clone git://github.com/haarg/perl-travis-helper
  - source perl-travis-helper/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - AUTHOR_TESTING=0 cpan-install "TOBYINK/Alt-Module-Runtime-ButEUMM-0.001.tar.gz"
  - AUTHOR_TESTING=0 cpan-install "TOBYINK/Alt-Class-Tiny-ButPerl56-0.001.tar.gz"
  - cpan-install --toolchain
  - cpan-install --deps
  - cpan-install --coverage
before_script:
  - coverage-setup
script:
  - prove -l -r "t"
after_success:
  - coverage-report
